AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for emlo_s12

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
  Api:
    BinaryMediaTypes:
    - "*/*"

Resources:
  EMLOS12Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        All:
          Type: Api 
          Properties:
            Path:  /{proxy+}
            Method: ANY
        Root:
          Type: Api 
          Properties:
            Path: /
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.10-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EMLOS12Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  EMLOS12FunctionArn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt EMLOS12Function.Arn
  EMLOS12FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt EMLOS12FunctionRole.Arn
